/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as StudyListRouteImport } from './routes/study.list'
import { Route as StudyFlashcardsRouteImport } from './routes/study.flashcards'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyRoute,
} as any)
const StudyListRoute = StudyListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => StudyRoute,
} as any)
const StudyFlashcardsRoute = StudyFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => StudyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/study': typeof StudyRouteWithChildren
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/list': typeof StudyListRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/list': typeof StudyListRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/study': typeof StudyRouteWithChildren
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/list': typeof StudyListRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/study'
    | '/study/flashcards'
    | '/study/list'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/study/flashcards' | '/study/list' | '/study'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/study'
    | '/study/flashcards'
    | '/study/list'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StudyRoute: typeof StudyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/list': {
      id: '/study/list'
      path: '/list'
      fullPath: '/study/list'
      preLoaderRoute: typeof StudyListRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/flashcards': {
      id: '/study/flashcards'
      path: '/flashcards'
      fullPath: '/study/flashcards'
      preLoaderRoute: typeof StudyFlashcardsRouteImport
      parentRoute: typeof StudyRoute
    }
  }
}

interface StudyRouteChildren {
  StudyFlashcardsRoute: typeof StudyFlashcardsRoute
  StudyListRoute: typeof StudyListRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyFlashcardsRoute: StudyFlashcardsRoute,
  StudyListRoute: StudyListRoute,
  StudyIndexRoute: StudyIndexRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StudyRoute: StudyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
