/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudyVocabRouteImport } from './routes/study.vocab'
import { Route as StudyReading3RouteImport } from './routes/study.reading3'
import { Route as StudyReading2RouteImport } from './routes/study.reading2'
import { Route as StudyQuizRouteImport } from './routes/study.quiz'
import { Route as StudyListRouteImport } from './routes/study.list'
import { Route as StudyFlashcardsRouteImport } from './routes/study.flashcards'
import { Route as AdminWordsRouteImport } from './routes/admin.words'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminProgressRouteImport } from './routes/admin.progress'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudyVocabRoute = StudyVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => StudyRoute,
} as any)
const StudyReading3Route = StudyReading3RouteImport.update({
  id: '/reading3',
  path: '/reading3',
  getParentRoute: () => StudyRoute,
} as any)
const StudyReading2Route = StudyReading2RouteImport.update({
  id: '/reading2',
  path: '/reading2',
  getParentRoute: () => StudyRoute,
} as any)
const StudyQuizRoute = StudyQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => StudyRoute,
} as any)
const StudyListRoute = StudyListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => StudyRoute,
} as any)
const StudyFlashcardsRoute = StudyFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => StudyRoute,
} as any)
const AdminWordsRoute = AdminWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgressRoute = AdminProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study': typeof StudyRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/words': typeof AdminWordsRoute
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/list': typeof StudyListRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/reading2': typeof StudyReading2Route
  '/study/reading3': typeof StudyReading3Route
  '/study/vocab': typeof StudyVocabRoute
  '/admin/': typeof AdminIndexRoute
  '/study/': typeof StudyIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/words': typeof AdminWordsRoute
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/list': typeof StudyListRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/reading2': typeof StudyReading2Route
  '/study/reading3': typeof StudyReading3Route
  '/study/vocab': typeof StudyVocabRoute
  '/admin': typeof AdminIndexRoute
  '/study': typeof StudyIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study': typeof StudyRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/words': typeof AdminWordsRoute
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/list': typeof StudyListRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/reading2': typeof StudyReading2Route
  '/study/reading3': typeof StudyReading3Route
  '/study/vocab': typeof StudyVocabRoute
  '/admin/': typeof AdminIndexRoute
  '/study/': typeof StudyIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/study'
    | '/admin/analytics'
    | '/admin/progress'
    | '/admin/upload'
    | '/admin/words'
    | '/study/flashcards'
    | '/study/list'
    | '/study/quiz'
    | '/study/reading2'
    | '/study/reading3'
    | '/study/vocab'
    | '/admin/'
    | '/study/'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/progress'
    | '/admin/upload'
    | '/admin/words'
    | '/study/flashcards'
    | '/study/list'
    | '/study/quiz'
    | '/study/reading2'
    | '/study/reading3'
    | '/study/vocab'
    | '/admin'
    | '/study'
    | '/api/public/track'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/study'
    | '/admin/analytics'
    | '/admin/progress'
    | '/admin/upload'
    | '/admin/words'
    | '/study/flashcards'
    | '/study/list'
    | '/study/quiz'
    | '/study/reading2'
    | '/study/reading3'
    | '/study/vocab'
    | '/admin/'
    | '/study/'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyRoute: typeof StudyRouteWithChildren
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof StudyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/study/vocab': {
      id: '/study/vocab'
      path: '/vocab'
      fullPath: '/study/vocab'
      preLoaderRoute: typeof StudyVocabRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/reading3': {
      id: '/study/reading3'
      path: '/reading3'
      fullPath: '/study/reading3'
      preLoaderRoute: typeof StudyReading3RouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/reading2': {
      id: '/study/reading2'
      path: '/reading2'
      fullPath: '/study/reading2'
      preLoaderRoute: typeof StudyReading2RouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/quiz': {
      id: '/study/quiz'
      path: '/quiz'
      fullPath: '/study/quiz'
      preLoaderRoute: typeof StudyQuizRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/list': {
      id: '/study/list'
      path: '/list'
      fullPath: '/study/list'
      preLoaderRoute: typeof StudyListRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/flashcards': {
      id: '/study/flashcards'
      path: '/flashcards'
      fullPath: '/study/flashcards'
      preLoaderRoute: typeof StudyFlashcardsRouteImport
      parentRoute: typeof StudyRoute
    }
    '/admin/words': {
      id: '/admin/words'
      path: '/words'
      fullPath: '/admin/words'
      preLoaderRoute: typeof AdminWordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/progress': {
      id: '/admin/progress'
      path: '/progress'
      fullPath: '/admin/progress'
      preLoaderRoute: typeof AdminProgressRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminProgressRoute: typeof AdminProgressRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminWordsRoute: typeof AdminWordsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminProgressRoute: AdminProgressRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminWordsRoute: AdminWordsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudyRouteChildren {
  StudyFlashcardsRoute: typeof StudyFlashcardsRoute
  StudyListRoute: typeof StudyListRoute
  StudyQuizRoute: typeof StudyQuizRoute
  StudyReading2Route: typeof StudyReading2Route
  StudyReading3Route: typeof StudyReading3Route
  StudyVocabRoute: typeof StudyVocabRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyFlashcardsRoute: StudyFlashcardsRoute,
  StudyListRoute: StudyListRoute,
  StudyQuizRoute: StudyQuizRoute,
  StudyReading2Route: StudyReading2Route,
  StudyReading3Route: StudyReading3Route,
  StudyVocabRoute: StudyVocabRoute,
  StudyIndexRoute: StudyIndexRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyRoute: StudyRouteWithChildren,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
